auctions/urls.py
from django.urls import path

from . import views

app_name="auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("list/<int:list_id>", views.getlist, name="list"),
    path("<int:list_id>/watchlist_add", views.watchlist_add, name="watchlist_add"),
    path("<int:list_id>/watchlist_remove", views.watchlist_remove, name="watchlist_remove"),
    path("<int:list_id>/comment", views.comment, name="comment"),
    path("<int:list_id>/bid", views.bid, name="bid"),
    path("<int:list_id>/close", views.close, name="close"),
    path("categories", views.categories, name="categories"),
    path("categories/<int:cat_id>", views.getcategory, name="getcategory"),
    path("mylist", views.mylist, name="mylist"),
    path("search", views.search, name="search")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

class User(AbstractUser):
    pass

class Category(models.Model):
    name = models.CharField(max_length=15)

    def __str__(self):
        return self.name

class Auction(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="auction")
    title = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    image = models.URLField()
    content = models.TextField()
    starting_price = models.DecimalField(max_digits=10, decimal_places=2)
    current_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=None)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"Auction number {self.id} : {self.title} published on {self.date} by {self.author}. Starting price : ${self.starting_price} - Category : {self.category}"

class Bid(models.Model):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="bid")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Bid for auction number {self.auction.id} - {self.auction.title} of ${self.amount} made by {self.author} on {self.date}"

class Comment(models.Model):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="comment")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return f"{self.author} commented on {self.auction.title} : {self.content}"

class Watchlist(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ManyToManyField(Auction, blank=True)

    def __str__(self):
        return f"Watchlist of user {self.owner}"

auctions/forms.py
from django import forms
from django.utils.safestring import mark_safe
from .models import User, Auction, Category, Comment, Bid

class CreateForm(forms.ModelForm):
    title = forms.CharField(label=mark_safe("<strong>Title</strong>"),
                            min_length=1,
                            max_length=100,
                            widget=forms.TextInput
                            (attrs={'class':'form-control',
				            'placeholder':'Title'
                            }))

    image = forms.URLField(label=mark_safe("<strong>Image URL</strong>"),
                            max_length=1000,
                            widget=forms.URLInput
                            (attrs={'class':'form-control',
                            'placeholder':'Image URL'
                            }))

    content = forms.CharField(label=mark_safe("<strong>Content</strong>"),
                            min_length=20,
                            max_length=1000,
                            widget=forms.Textarea
                            (attrs={'class':'form-control',
				            'placeholder':'Content'
                            }))

    starting_price = forms.DecimalField(label=mark_safe("<strong>Starting price (USD)</strong>"),
                            min_value=0.01,
                            widget=forms.NumberInput
                            (attrs={'class':'form-control',
				            'placeholder':'Starting price'
                            }))

    category = forms.ModelChoiceField(queryset=Category.objects.all(),
                            label=mark_safe("<strong>Category</strong>"),
                            required=True,
                            widget= forms.Select
                            (attrs={'class':'form-control'
                            }))
                            
    class Meta:
        model = Auction
        exclude = ["author", "date", "active", "current_price"]

class CommentForm(forms.ModelForm):
    content = forms.CharField(label=mark_safe("<strong>Type your comment below</strong>"),
                            min_length=1,
                            max_length=100,
                            widget=forms.TextInput
                            (attrs={'class':'form-control mb-2',
				            'placeholder':'Your comment'
                            }))
                            
    class Meta:
        model = Comment
        exclude = ["auction", "author", "date"]

class BidForm(forms.ModelForm):
    amount = forms.DecimalField(label=mark_safe("<strong>Place your bid</strong>"),
                            min_value=0.01,
                            widget=forms.NumberInput
                            (attrs={'class':'form-control',
				            'placeholder':'Bid amount'
                            }))
                            
    class Meta:
        model = Bid
        exclude = ["auction", "author", "date"]

class SearchForm(forms.Form):
    search = forms.CharField(label="",
                            min_length=1,
                            max_length=50,
                            widget=forms.TextInput
                            (attrs={'class':'form-control mr-sm-2',
				            'placeholder':'Name or category',
                            'type':'search',
                            'aria-label':'Search'
                            }))

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django import forms
from django.utils.safestring import mark_safe
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist

from .models import User, Category, Auction, Bid, Comment, Watchlist
from .forms import CreateForm, CommentForm, BidForm, SearchForm

def index(request):
    auctions = Auction.objects.filter(active=True).order_by("-date")
    return render(request, "auctions/index.html", {
        "auctions": auctions,
        "searchform": SearchForm()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            messages.add_message(request, message.ERROR, 'Invalid username and/or password.')
            return HttpResponseRedirect(reverse("auctions:login"))
    else:
        return render(request, "auctions/login.html", {
            "searchform": SearchForm()
        })


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            messages.add_message(request, message.ERROR, 'Passwords must match.')
            return HttpResponseRedirect(reverse("auctions:register"))

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            messages.add_message(request, message.ERROR, 'Username already taken.')
            return HttpResponseRedirect(reverse("auctions:register"))
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html", {
            "searchform": SearchForm()
        })


@login_required(redirect_field_name='')
def create(request):
    if request.method == "POST":
        form = CreateForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.author = request.user
            data.save()
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/create.html", {
                "createform": form,
                "searchform": SearchForm()
            })

    else:
        return render(request, "auctions/create.html", {
        "createform": CreateForm()
        })

@login_required(redirect_field_name='')
def getlist(request, list_id):
    auction = Auction.objects.get(pk=list_id)
    comments = Comment.objects.filter(auction_id=list_id).order_by('-date')
    highestbid = Bid.objects.filter(auction_id=list_id).order_by('-amount').first()
    return render(request, "auctions/list.html", {
        "auction": auction,
        "comments": comments,
        "commentform": CommentForm(),
        "bidform": BidForm(),
        "highestbid": highestbid,
        "searchform": SearchForm()
    })

@login_required(redirect_field_name='')
def watchlist_add(request, list_id):
    if request.method == "POST":
        auction = Auction.objects.get(pk=list_id)
        check = Watchlist.objects.filter(id=request.user.id, product=list_id).first()
        if check is not None:
            messages.add_message(request, messages.WARNING, 'This auction is already in your watchlist.')
            return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
        else:
            try:
                usrlist = Watchlist.objects.get(id=request.user.id)
                usrlist.product.add(auction)
                usrlist.save()
                messages.add_message(request, messages.SUCCESS, 'Successfully added to your watchlist.')
                return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
            except ObjectDoesNotExist:
                usrlist = Watchlist(id=request.user.id, owner_id=request.user.id)
                usrlist.save()
                usrlist.product.add(auction)
                messages.add_message(request, messages.SUCCESS, 'Successfully added to your watchlist.')
                return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
        

@login_required(redirect_field_name='')
def watchlist_remove(request, list_id):
    if request.method == "POST":
        auction = Auction.objects.get(pk=list_id)
        check = Watchlist.objects.filter(id=request.user.id, product=list_id).first()
        if check is None:
            messages.add_message(request, messages.WARNING, 'This auction is not in your watchlist.')
            return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
        else:
            try:
                usrlist = Watchlist.objects.get(id=request.user.id)
                usrlist.product.remove(auction)
                usrlist.save()
                messages.add_message(request, messages.ERROR, 'Successfully removed from your watchlist.')
                return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
            except ObjectDoesNotExist:
                messages.add_message(request, messages.WARNING, 'This auction is not in your watchlist.')
                return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
                
@login_required(redirect_field_name='')
def comment(request, list_id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            auction = Auction.objects.get(pk=list_id)
            data = form.save(commit=False)
            data.author = request.user
            data.auction = auction
            data.save()
            messages.add_message(request, messages.SUCCESS, "Your comment was successfully posted.")
            return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
        else:
            messages.add_message(request, messages.ERROR, "Your comment form is invalid.")
            return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))

@login_required(redirect_field_name='')
def bid(request, list_id):
    if request.method == "POST":
        form = BidForm(request.POST)
        if form.is_valid():
            bidamount = form.cleaned_data["amount"]
            auction = Auction.objects.get(pk=list_id)
            if request.user.id == auction.author_id:
                messages.add_message(request, messages.ERROR, "You can't bid on your own auction.")
                return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
            if not auction.active:
                messages.add_message(request, messages.ERROR, "You can't bid on a closed auction.")
                return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
            if bidamount <= auction.starting_price:
                messages.add_message(request, messages.ERROR, "You must place a higher bid than the current price.")
                return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
            higherbid = Bid.objects.filter(auction_id=list_id).order_by('-amount').first()
            if higherbid is not None:
                if bidamount <= higherbid.amount:
                    messages.add_message(request, messages.ERROR, "You must place a higher bid than the current price.")
                    return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
                else:
                    data = form.save(commit=False)
                    auction.current_price = bidamount
                    data.author_id = request.user.id
                    data.auction_id = list_id
                    data.save()
                    auction.save()
                    messages.add_message(request, messages.SUCCESS, "Your bid was successfully placed :)")
                    return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
            else:
                data = form.save(commit=False)
                auction.current_price = bidamount
                data.author_id = request.user.id
                data.auction_id = list_id
                data.save()
                auction.save()
                messages.add_message(request, messages.SUCCESS, "Your bid was successfully placed :)")
                return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))
        else:
            messages.add_message(request, messages.ERROR, "Your form is invalid.")
            return HttpResponseRedirect(reverse("auctions:list", args=(list_id,)))

def categories(request):
    categories = Category.objects.all().order_by("name")
    return render(request, "auctions/categories.html", {
        "categories": categories,
        "searchform": SearchForm()
    })

@login_required(redirect_field_name='')
def mylist(request):
    auctions = Auction.objects.filter(watchlist__id=request.user.id, active=True)
    return render(request, "auctions/mylist.html", {
        "auctions": auctions,
        "searchform": SearchForm()
    })

def getcategory(request, cat_id):
    auctions = Auction.objects.filter(category_id=cat_id).order_by('-date')
    category = Category.objects.get(id=cat_id)

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block title %}
    Category {{ category.name }}
{% endblock %}

{% block cardtitle %}
    Browse Category - {{ category.name }}
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title text-center">See below all this category's listings (from the most recent) :</h5>
            <div class="card-text">
                {% for auction in auctions %}
                <div class="card mb-2">
                  <a href="{% url 'auctions:list' auction.id %}">
                    <img src="{{ auction.image }}" class="card-img-top" alt="Auction {{ auction.id }} image">
                  </a>
                  <div class="card-body">
                    <a href="{% url 'auctions:list' auction.id %}">
                      <h5 class="card-title text-center">{{ auction.title }}</h5>
                    </a>
                    <div class="text-center">
                      Auction status : {% if auction.active %} <div class="mb-1" style="font-weight: bold; color: green;">Active</div>{% else %}<div class="mb-1" style="font-weight: bold; color: red;">Finished</div>{% endif %}
                    </div>
                    <hr>
                    <p class="card-text">{{ auction.content }}</p>
                    <br>
                    Starting price : <strong>{{ auction.starting_price }} USD.</strong>
                    <br>
                    {% if auction.active %}Current{% else %}Final{% endif %} price : {% if auction.current_price is not None %}<strong style="color: green;">{{ auction.current_price }} USD</strong>.{% else %} No bids made on this auction.{% endif %}
                    <small class="float-right">
                      Category : <strong>{{ auction.category }}</strong>
                    </small>
                    <hr>
                    <div class="text-center">
                        {% if user.is_authenticated %}
                          <form action="{% url 'auctions:list' auction.id %}">
                            <input class="btn btn-primary mb-2" type="submit" value="Go to Auction Page">
                          </form>
                          {% if auction.active %}
                          <form action="{% url 'auctions:watchlist_add' auction.id %}" method="POST">
                            {% csrf_token %}
                            <input class="btn btn-warning mb-1" type="submit" value="Add to watchlist">
                          </form>
                          <form action="{% url 'auctions:watchlist_remove' auction.id %}" method="POST">
                            {% csrf_token %}
                            <input class="btn btn-danger" type="submit" value="Remove from watchlist">
                          </form>
                          {% endif %}
                        {% else %}
                        <div class="text-center">
                          <form action="{% url 'auctions:list' auction.id %}">
                            <input class="btn btn-primary mb-2" type="submit" value="Register or Login to participate">
                          </form>
                        </div>
                        {% endif %}
                    </div>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted">Posted by <strong>{{ auction.author }}</strong> on {{ auction.date }}</small>
                  </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Auctions - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'auctions/css/bootstrap.min.css' %}">
        <link rel="shortcut icon" href="{% static 'auctions/img/auctionslogo.png' %}" type="image/x-icon">
    </head>
    <body class="bg-dark">
        <header class="mb-3">
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary p-3">
                <a class="navbar-brand mr-3 px-3" href="{% url 'auctions:index' %}">
                    <img src="{% static 'auctions/img/auctionslogo.png' %}" class="d-inline-block" alt="Auctions Logo" loading="lazy">
                    Auctions
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-1">
                        <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'auctions:index' %}">Home<span class="sr-only">(current)</span></a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item {% if request.path == '/create' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'auctions:create' %}">Create list</a>
                            </li>
                            <li class="nav-item {% if request.path == '/categories' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                            </li>
                            <li class="nav-item {% if request.path == '/mylist' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'auctions:mylist' %}">Watchlist</a>
                            </li>
                            <li class="nav-item {% if request.path == '/logout' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'auctions:logout' %}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item {% if request.path == '/categories' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                            </li>
                            <li class="nav-item {% if request.path == '/login' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'auctions:login' %}">Login</a>
                            </li>
                            <li class="nav-item {% if request.path == '/register' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                    <span class="navbar-text mr-auto text-white" style="font-size: 0.8rem;">
                        {% if user.is_authenticated %}
                            Signed in as <strong>{{ user.username }}</strong>.
                        {% else %}
                            Not signed in.
                        {% endif %}
                    </span>
                    <form class="form-inline my-2 my-lg-0" action="{% url 'auctions:search' %}" method="POST">
                        {% csrf_token %}
                        {{ searchform.search }}
                        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </header>
        <div class="container">
            {% if messages %}
                    {% for message in messages %}
                    <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </div>
                    {% endfor %}
            {% endif %}
            <div class="card bg-light mb-3">
                <div class="text-center">
                    <div class="card-header text-primary" style="line-height: 4rem; font-size: 2rem; font-weight: bold;">{% block cardtitle %}{% endblock %}</div>
                </div>
                <div class="card-body">
                  <div class="card-text">{% block body %}{% endblock %}</div>
                </div>
            </div>
        </div>
        <footer class="page-footer font-small bg-secondary">
            <div class="footer footer-copyright text-center">© 2020 Copyright:
              <a class="btn text-white" href="{% url 'auctions:index' %}"> Auctions.cs50</a>
            </div>
        </footer>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="{% static 'auctions/js/bootstrap.min.js' %}"></script>
    </body>
</html>

auctions/templates/auctions/list.html
{% extends "auctions/layout.html" %}

{% block title %}
    Number {{ auction.id }}
{% endblock %}

{% block cardtitle %}
    {{ auction.title }}
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header text-white bg-primary">
            Auction details
        </div>
        <div class="card-body">
            <h5 class="card-title text-center">Auction reference number {{ auction.id }} - {{ auction.title }} | Seller : <strong>{{ auction.author }}</strong></h5>
            {% if request.user.id == auction.author_id and auction.active %}
                <form action="{% url 'auctions:close' auction.id %}" method="POST">
                    {% csrf_token %}
                    <div class="text-center">
                        <input class="btn btn-danger btn-lg" type="submit" value="Close this auction">
                    </div>
                </form>
            {% endif %}
            <hr>
            <div class="text-center">
                Auction status : {% if auction.active %} <div class="mb-1" style="font-weight: bold; color: green;">Active</div>{% else %}<div class="mb-1" style="font-weight: bold; color: red;">Finished</div>{% endif %}
                {% if highestbid and auction.active == False %}Winner of this auction :<div class="mb-1" style="font-weight: bold; color: green;">{{ highestbid.author }}</div>Final bid : <div class="mb-1" style="font-weight: bold; color: green;">{{ highestbid.amount }} USD</div>{% elif highestbid is None and auction.active == False %}
                <div class="mb-1" style="font-weight: bold; color: red;">Nobody</div>the seller closed before the first bid.{% endif %}
            </div>
            <div class="card-text">
                <div class="card mb-2">
                  <img src="{{ auction.image }}" class="card-img-top" alt="Auction {{ auction.id }} image">
                  <div class="card-body">
                    <h5 class="card-title text-center">{{ auction.title }}</h5>
                    <hr>
                    <p class="card-text">{{ auction.content }}</p>
                    <br>
                    Starting price : <strong>{{ auction.starting_price }} USD</strong>
                    <br>
                    {% if auction.active %}Current{% else %}Final{% endif %} price : {% if highestbid %}<strong style="color: green;">{{ highestbid.amount }} USD</strong> - highest bid made by <strong>{{ highestbid.author }}</strong>.{% else %} No bids made on this auction.{% endif %}
                    <small class="float-right">
                        Category : <strong>{{ auction.category }}</strong>
                    </small>
                    {% if request.user.id != auction.author_id and auction.active %}
                        <hr>
                        <div class="text-center">
                            <form action="{% url 'auctions:bid' auction.id %}" method="POST">
                                {% csrf_token %}
                                {{ bidform.amount }}
                            <input class="btn btn-success mb-2 mt-2" type="submit" value="Bid">
                            </form>
                        </div>
                    {% endif %}
                    <div class="text-center">
                        <form action="{% url 'auctions:watchlist_add' auction.id %}" method="POST">
                            {% csrf_token %}
                            <input class="btn btn-warning mb-1" type="submit" value="Add to watchlist">
                        </form>
                        <form action="{% url 'auctions:watchlist_remove' auction.id %}" method="POST">
                            {% csrf_token %}
                            <input class="btn btn-danger" type="submit" value="Remove from watchlist">
                        </form>
                    </div>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted">Posted by <strong>{{ auction.author }}</strong> on {{ auction.date }}</small>
                  </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header text-white bg-primary" style="text-align: right;">
            Auction comments
        </div>
        <div class="card-body">
            {% if comments %}
                <h5 class="card-title">Comments posted on this auction :</h5>
                {% for comment in comments %}
                    <div class="card-text">
                        <div class="card mb-2">
                        <div class="card-body">
                            <p class="card-text">{{ comment.content }}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Posted by <strong>{{ comment.author }}</strong> on {{ comment.date }}</small>
                        </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h5 class="card-title">No comments posted on this auction.</h5>   
            {% endif %}
        </div>
        {% if auction.active %}
        <div class="form-group">
            <form action="{% url 'auctions:comment' auction.id %}" method="POST">
            {% csrf_token %}
            {{ commentform.content }}
            <div class="text-center">
                <input class="btn btn-primary mb-2" type="submit" value="Add a new comment">
            </div>
            </form>
        </div>
        {% endif %}
    </div>

{% endblock %}